name: Test Examples
on:
  push:
    branches:
      - master
  pull_request:
env:
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ${{ matrix.platform }}
    name: "${{ matrix.example }} - ${{ matrix.platform }}"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        toolchain: [1.81]
        # toolchain: [stable]
        example: [
          adder,
          callback-results,
          cross-contract-calls,
          factory-contract,
          fungible-token,
          non-fungible-token,
          versioned          
        ]
    steps:
      - uses: actions/checkout@v3
      - name: "${{ matrix.toolchain }} with rustfmt, and wasm32"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./examples/${{ matrix.example }}
      - name: Build status-message, factory-contract && test factory-contract
        if: matrix.example == 'factory-contract'
        env:
          RUSTFLAGS: '-C link-arg=-s'
        run: |
          cargo +${{ matrix.toolchain }} build --manifest-path="./examples/status-message/Cargo.toml" --target wasm32-unknown-unknown --release --all
          cp ./examples/status-message/target/wasm32-unknown-unknown/release/*.wasm ./examples/status-message/res/
          cargo +${{ matrix.toolchain }} build --manifest-path=./examples/factory-contract/Cargo.toml --target wasm32-unknown-unknown --release --all
          cp ./examples/factory-contract/target/wasm32-unknown-unknown/release/*.wasm ./examples/factory-contract/res/
          cargo +${{ matrix.toolchain }} test --manifest-path=./examples/factory-contract/Cargo.toml --all
      - name: Build
        env:
          RUSTFLAGS: '-C link-arg=-s'
        run: |
          cargo +${{ matrix.toolchain }} build --manifest-path="./examples/${{matrix.example}}/Cargo.toml" --target wasm32-unknown-unknown --release --all &&
          cp ./examples/${{matrix.example}}/target/wasm32-unknown-unknown/release/*.wasm ./examples/${{matrix.example}}/res/
      - name: Test
        run: cargo +${{ matrix.toolchain }} test --manifest-path="./examples/${{ matrix.example }}/Cargo.toml" --all
